### PR TITLE
Allow wildcards in 'test-only' (closes #28)

### LINKED ISSUE #28: Allow wildcards in 'test-only'
So I can type `multi-jvm:testOnly *RemoteRe*` rather than `multi-jvm:testOnly akka.remote.RemoteReDeployment`

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by ktoso** [comment]
Please add refs #28 :)

Awesome if that's all that was needed to make it work :)

**Comment by 2m** [comment]
LGTM

**Comment by 2m** [comment]
Closing/opening to check out Travis.

**Comment by 2m** [comment]
LGTM

**Pull request merged**
